POST https://api.hubapi.com/crm/v3/objects/contacts/search
Authorization: Bearer {{HUBSPOT_API_KEY}}
Content-Type: application/json
{
    "filterGroups": [
        {
            "filters": [
                {
                    "propertyName": "email",
                    "operator": "EQ",
                    "value": "ethanmdev@gmail.com"
                }
            ]
        }
    ],
    "properties": [
        "email",
        "firstname",
        "lastname",
        "phone",
        "address",
        "city",
        "state",
        "country",
        "hubspot_owner_id",
        "contact_id"
    ],
    "limit": 100
}